---
- name: Installing php56 php-ppa
  apt_repository: repo='ppa:ondrej/php5-5.6'

- name: Installing php55 packages
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - php5
    - php5-json
    - apache2
  notify:
    - start apache2
