---
- name: Installing dependency mirros
  yum: name={{ item }} state=present
  with_items:
    - https://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm
    - http://rpms.remirepo.net/enterprise/remi-release-7.rpm

- name: Enabling Remis repo
  template: src=centos7remi.repo.j2 dest=/etc/yum.repos.d/remi.repo owner=root group=root mode=0644

- name: Installing php56 packages
  yum: name={{ item }} state=present
  with_items:
    - "{{ php.php56packages }}"

- name: Configuring php
  template:
    src: php.conf.j2
    dest: /etc/httpd/conf.d/php.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart httpd
